# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'adminApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for adminApp

  # target 'adminApp-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  pod 'react-native-material-kit', :path => '../node_modules/react-native-material-kit'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'adminAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'Firebase/Auth'
pod 'Firebase/Functions'
pod 'Firebase/Messaging'
pod 'Firebase/Storage'
end

# target 'adminApp-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for adminApp-tvOS

#   target 'adminApp-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
